
### API 1
GET http://localhost:3000/states/

### API 2
GET http://localhost:3000/states/2/

### API 3
POST http://localhost:3000/districts/
Content-Length: application/json

{
  "districtName": "Bagalkot",
  "stateId": 5,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}

### API 4
GET http://localhost:3000/districts/:districtId/

### API 5
DELETE http://localhost:3000/districts/:districtId/


### API 6
PUT http://localhost:3000/districts/2/
Content-Length: application/json

{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}

### API 7
GET http://localhost:3000/states/:stateId/stats/

### API 8
GET http://localhost:3000/districts/2/details/